---
output:
    pdf_document:
        dev: cairo_pdf
        latex_engine: xelatex
        fig_caption: yes
header-includes:
- \usepackage{titling}
- \setlength{\droptitle}{10em}
- \renewcommand{\caption}{}
- \usepackage[font=bf]{caption}
- \pagenumbering{gobble}
---

```{r dependencies, include=FALSE}
library("ggplot2")
library(cowplot)
library("dplyr")
library("survival")
library("knitr")
library("gridExtra")
library("tidyr")
library("kableExtra")
library("data.table")
options(warn=-1)
opts_chunk$set(dpi=300)
```

```{r echo= F}

d= fread(snakemake@input[[1]], h=F)
colnames(d)= c('Sub-cohort', 'Median', 'P25', 'P75')
d$Median= paste0(round(d$Median, 1), ' (', round(d$P25, 1), ', ', round(d$P75, 1), ')')
d= d[,c('Sub-cohort', 'Median')]
kable(d, align= c('l', 'c'), row.names= F, format="pandoc", caption = "S1 Table: Total parental identical-by-descent sharing, in cM.", col.names=c('Sub-cohort', 'Median (IQR)'), booktabs = T) %>% kable_styling(latex_options= c('striped')) %>% column_spec(1, bold = T, color = "black", background = "white") %>% footnote(general_title= '', general= c('cM, centiMorgans', 'Germline was used to identify identical-by-descent segments with a minimum detection of 2 cM.'), threeparttable=T)

```

