---
output:
    pdf_document:
        dev: cairo_pdf
        latex_engine: xelatex
        fig_caption: yes
header-includes:
- \usepackage{titling}
- \setlength{\droptitle}{10em}
- \renewcommand{\caption}{}
- \usepackage[font=bf]{caption}
- \pagenumbering{gobble}
---

```{r dependencies, include=FALSE}
library("ggplot2")
library(cowplot)
library("dplyr")
library("survival")
library("knitr")
library("gridExtra")
library("tidyr")
library("kableExtra")
library("data.table")
options(warn=-1)
opts_chunk$set(dpi=300)
```

```{r echo= F}

d= fread(snakemake@input[[1]], h=T)

d$beta= round(d$beta, 3)
d$se= round(d$se, 3)
d$exposure= ifelse(d$exposure== 'FKB', 'FROH', ifelse(d$exposure== 'KBAVG', 'Average segment length', ifelse(d$exposure== 'tmrca', 'TMRCA', ifelse(d$exposure== 'NSEG', 'N segments', d$exposure))))


d$Estimate= paste0(round(d$HR, 3), ' (', round(d$lowerci,3), ', ', round(d$upperci,3), ')')

d= select(d, sample, exposure, model, n, event, beta, se, Estimate, pvalue)

d= arrange(d, sample, exposure, desc(model))

kable(d, align= c('l', 'c', 'c', 'c', 'c', 'c', 'c', 'c'), row.names= F, col.names=c('Sample', 'Exposure', 'Model', 'N', 'Events', 'Beta', 'Standard Error', 'Estimate (95% CI)', 'P-value'), caption = "S4 Table: Autozygosity in mothers, fathers and fetuses and risk of spontaneous onset of delivery.", booktabs = T) %>% kable_styling(latex_options= c('striped', 'scale_down')) %>% column_spec(1, bold = T, color = "black", background = "white") %>% footnote(general_title= '', general= c('FHOM, excess homozygosity; FROH, proportion of the genome covered by autozygous segments', 'Crude model was adjusted by sub-cohort, and the adjusted model was adjusted for sub-cohort, the first 6 PC, parity, educational attainment and household income.'), threeparttable= T)

```

