---
output:
    pdf_document:
        dev: cairo_pdf
        latex_engine: xelatex
        fig_caption: yes
header-includes:
- \usepackage{titling}
- \setlength{\droptitle}{10em}
- \renewcommand{\caption}{}
- \usepackage[font=bf]{caption}
- \pagenumbering{gobble}
---

```{r dependencies, include=FALSE}
library("ggplot2")
library(cowplot)
library("dplyr")
library("survival")
library("knitr")
library("gridExtra")
library("tidyr")
library("kableExtra")
library("data.table")
options(warn=-1)
opts_chunk$set(dpi=300)
```

```{r echo= F}

d= fread(snakemake@input[[1]], h=T)
d$spont= with(d, paste0(spont_n, ' (', spont_frac, ')'))
d$ga= with(d, paste0(ga_mean, ' (', ga_sd, ')'))
d$parity= with(d, paste0(parity_n, ' (', parity_frac, ')'))
#d$bw= with(d, paste0(bw_mean, ' (', bw_sd, ')'))
d$age= with(d, paste0(age_mean, ' (', age_sd, ')'))
d$inc1= with(d, paste0(inc1_n, ' (', inc1_frac, ')'))
d$inc2= with(d, paste0(inc2_n, ' (', inc2_frac, ')'))
d$inc3= with(d, paste0(inc3_n, ' (', inc3_frac, ')'))
d$edu1= with(d, paste0(edu1_n, ' (', edu1_frac, ')'))
d$edu2= with(d, paste0(edu2_n, ' (', edu2_frac, ')'))
d$edu3= with(d, paste0(edu3_n, ' (', edu3_frac, ')'))

pval= fread(snakemake@input[[2]], h=T)


d= select(d, cohort, total_n, spont, ga, parity, age, inc1, inc2, inc3, edu1, edu2, edu3)
df= as.data.frame(t(d[,-1]))
colnames(df)= d$cohort

pval= formatC(pval$pvalue, format = "e", digits = 2)

df= cbind(df, c('', pval[1], pval[2], pval[3], pval[4], '', pval[5], '', '', pval[6], ''))

colnames(df)= c('Cohort1',   'Cohort2',   'Cohort3',   'Cohort4',   'Cohort5',   'Cohort6', 'P-value')

rownames(df)= c('Total n', 'Spontaneous delivery, n', 'Gestational duration, days', 'Nulliparous, n', 'Maternal age, years',  'Inc. 0 parents >300.000 kr', 'Inc. 1 parent >300.000 kr', 'Inc. 2 parents > 300.000 kr', 'Education ≤12 years', 'Education 13 to 16 years', 'Education ≥17 years')

#kable(df, row.names= T, booktabs = T, caption = "S1 Table: ", booktabs = T) %>% kable_styling(latex_options= c('striped', 'scale_down'), stripe_index= c(4:6, 8, 11)) %>% column_spec(1, bold = T, color = "black", background = "white")

kable(df, align= rep('c', 7), row.names= T, caption = "S5 Table: Descriptive characteristics of pregnancies in all sub-cohorts.", booktabs = T) %>% kable_styling(latex_options= c('striped', 'scale_down'), stripe_index= c(4:6, 8, 11)) %>% column_spec(1, bold = T, color = "black", background = "white") %>% footnote(general_title= '', general= c('Inc, income.','Spontaneous delivery was defined as a delivery not initiated by cesarean section nor induction. All data was obtained from the Medical Birth Registry of Norway, except household income and maternal educational attainment, which were obtained from a questionnaire filled by the mother in early pregnancy. P-values were obtianed using ANOVA and Chi² for continuous and categorical data, respectively.'), threeparttable= T) %>%   landscape()

```


