---
title: "**Estimated autozygosity in Norwegian family trios and its relation to the timing of birth.**"
author:
        - "Pol Sole-Navais"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    beamer_presentation:
        theme: "default"
        colortheme: "dove"
        fonttheme: "structuresmallcapsserif"
        slide_level: 2
        dev: png
---

```{r include=FALSE, echo=F}
library("ggplot2")
library("dplyr")
library("knitr")
library("gridExtra")
library("tidyr")
library("kableExtra")
library("data.table")
library("metafor")
options(warn=-1)
opts_chunk$set(dpi=300, out.width="300px")

bin_funk= function(x){
bin= diff(range(x, na.rm=T)) / (2 * IQR(x, na.rm= T) / length(x)^(1/3))
return(bin)
}

SelectRelated= function(kin, sample_list){
 kin= kin %>% filter(KINSHIP>0.0884)
 kin= kin %>% filter(ID1 %in% sample_list, ID2 %in% sample_list)
if (nrow(kin)>0){

 kin= kin %>% select(ID1, ID2, KINSHIP)
  kin_temp= kin
  colnames(kin_temp)= c("ID2","ID1","KINSHIP")
  kin_temp= rbind(kin_temp, kin)
  kin_temp= kin_temp %>% add_count(ID1)
  kin_temp= kin_temp %>% add_count(ID2)
  to_keep= list()

  for (i in 1:nrow(kin_temp)) {
    if (kin_temp[i,"ID1"] %in% unlist(kin_temp[0:i,"ID2"])) {
      kin_temp[i,"ID2"]= "X"
    }
    else
      to_keep[[i]] <- kin_temp[["ID1"]][i]
  }
  to_remove= kin_temp %>% filter(!(ID1 %in% unlist(to_keep))) %>% select(ID1)
  to_remove= to_remove[!duplicated(to_remove$ID1),]
  to_remove= to_remove %>% separate(ID1, c('FID','ID'), sep=":")

  return(unlist(to_remove[,1]))
}
}

input= snakemake@input

```



```{r echo=F}


h_all= list()
moms_all= list()
fets_all= list()
alldf_all= list()

for (coh in c('harvest')){
harvest_input= input[grep(coh, input)]

h1= fread(unlist(harvest_input[grep('h1', harvest_input)]))
h2= fread(unlist(harvest_input[grep('h2', harvest_input)]))
h3= fread(unlist(harvest_input[grep('h3', harvest_input)]))

fets= fread(unlist(harvest_input[grep('fets', harvest_input)]))
moms= fread(unlist(harvest_input[grep('moms', harvest_input)]))

fets= rename(fets, fets_height_GRS= height_GRS)
moms= rename(moms, moms_height_GRS= height_GRS)

link= fread(unlist(harvest_input[grep('linkage', harvest_input)]))
mfr= fread(unlist(harvest_input[grep('mfr', harvest_input)]))
kin= fread(unlist(harvest_input[grep('relatedness', harvest_input)]))

q1= fread(unlist(harvest_input[grep('q1_v9', harvest_input)]))

flag= fread(unlist(harvest_input[grep('flag_list.txt', harvest_input)]))

flag= filter(flag, genotypesOK== TRUE, coreOK== TRUE, phenotypesOK== TRUE)

h= full_join(h1, h2, by= 'PREG_ID_1724') %>% full_join(., h3, by= 'PREG_ID_1724')

mfr= mutate(mfr, spont= as.numeric(FSTART==1 & (is.na(KSNITT) | KSNITT>1) &
                (is.na(KSNITT_PLANLAGT) | KSNITT_PLANLAGT==1) &
                INDUKSJON_PROSTAGLANDIN==0 &
                INDUKSJON_ANNET==0 &
                INDUKSJON_OXYTOCIN==0 &
                INDUKSJON_AMNIOTOMI==0),
                PARITY0= as.numeric(PARITET_5==0))

mfr= filter(mfr, FLERFODSEL==0 ,
                        DODKAT<6 | DODKAT>10,
                        !is.na(SVLEN_UL_DG),
                        SVLEN_UL_DG<308 &
                        SVLEN_UL_DG>154)

mfr= mfr[order(mfr$spont, decreasing= T),]

mfr = filter(mfr, is.na(IVF),ABRUPTIOP==0,
                           PLACENTA_PREVIA==0,
                        FOSTERV_POLYHYDRAMNION==0,
C00_MALF_ALL==0)

mfr= filter(mfr, spont== 1)

q1= q1 %>% mutate(
                height= ifelse(AA87>= 140 & AA87<= 210, AA87, NA),
                bmi= AA85/ ((height/100)^2),
                bmi= ifelse(bmi>15 | bmi< 45, bmi, NA))

q1= q1 %>% select(PREG_ID_1724, height, AA83, AA84, bmi)

h= inner_join(h, mfr, by= 'PREG_ID_1724') %>% inner_join(., q1, by= 'PREG_ID_1724') %>% inner_join(., filter(link, Role== 'Child'), by= 'PREG_ID_1724')

fets= inner_join(fets, link, by= 'SentrixID_1') %>% inner_join(., mfr, by= 'PREG_ID_1724') %>% inner_join(., q1, by= 'PREG_ID_1724')
moms= inner_join(moms, link, by= 'SentrixID_1') %>% inner_join(., mfr, by= 'PREG_ID_1724') %>% inner_join(., q1, by= 'PREG_ID_1724')

moms= filter(moms, SentrixID_1 %in% flag$IID)
fets= filter(fets, SentrixID_1 %in% flag$IID)
h= filter(h, SentrixID_1 %in% flag$IID)


moms= moms %>% filter(!(SentrixID_1 %in% SelectRelated(kin, moms$SentrixID_1)))

fets= fets %>% filter(!(SentrixID_1 %in% SelectRelated(kin, fets$SentrixID_1)))

h= h %>% filter(!(SentrixID_1 %in% SelectRelated(kin, h$SentrixID_1)))

df_all= inner_join(moms, fets, by= 'PREG_ID_1724') %>% inner_join(., h, by= 'PREG_ID_1724')

fets= select(fets, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, fets_height_GRS)
moms= select(moms, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, moms_height_GRS)
h= select(h, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, h1_height_GRS, h2_height_GRS, h3_height_GRS)
df_all= select(df_all, fets_height_GRS, moms_height_GRS, h1_height_GRS, h2_height_GRS, h3_height_GRS)


fets$cohort= coh
moms$cohort= coh
h$cohort= coh
df_all$cohort= coh



h_all= c(h_all, list(h))
moms_all= c(moms_all,  list(moms))
fets_all= c(fets_all, list(fets))
alldf_all= c(alldf_all, list(df_all))

}

```

```{r echo=F}

for (coh in c('rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay')){
harvest_input= input[grep(coh, input)]

h1= fread(unlist(harvest_input[grep('h1', harvest_input)]))
h2= fread(unlist(harvest_input[grep('h2', harvest_input)]))
h3= fread(unlist(harvest_input[grep('h3', harvest_input)]))

fets= fread(unlist(harvest_input[grep('fets', harvest_input)]))
moms= fread(unlist(harvest_input[grep('moms', harvest_input)]))

fets= rename(fets, fets_height_GRS= height_GRS)
moms= rename(moms, moms_height_GRS= height_GRS)

link= fread(unlist(harvest_input[grep('linkage', harvest_input)]))
mfr= fread(unlist(harvest_input[grep('mfr', harvest_input)]))
kin= fread(unlist(harvest_input[grep('relatedness', harvest_input)]))

q1= fread(unlist(harvest_input[grep('q1_v9', harvest_input)]))


flag= fread(unlist(harvest_input[grep('flag_list.txt', harvest_input)]))
flag= filter(flag, genotypesOK== TRUE, coreLMM== TRUE, phenoOK== TRUE)

h= full_join(h1, h2, by= 'PREG_ID_315') %>% full_join(., h3, by= 'PREG_ID_315')

mfr= mutate(mfr, spont= as.numeric((FSTART=='Spontan' | is.na(FSTART) | FSTART== '') & (is.na(KSNITT) | KSNITT== '' | KSNITT== 'Uspesifisert keisersnitt' | KSNITT== 'Akutt keisersnitt') &
                INDUKSJON_PROSTAGLANDIN=='Nei' &
                INDUKSJON_ANNET=='Nei' &
                INDUKSJON_OXYTOCIN=='Nei' &
                INDUKSJON_AMNIOTOMI=='Nei'),
PARITY0= as.numeric(PARITET_5=='0 (førstegangsfødende)'))

mfr= filter(mfr, FLERFODSEL== 'Enkeltfødsel' ,
                        grepl('Levendefødt', DODKAT),
                        !is.na(SVLEN_UL_DG),
                        SVLEN_UL_DG<308 &
                        SVLEN_UL_DG>154)

mfr= mfr[order(mfr$spont, decreasing= T),]

mfr = filter(mfr, is.na(IVF) | IVF== '',ABRUPTIOP=='Nei',
                           PLACENTA_PREVIA=='Nei',
                        FOSTERV_POLYHYDRAMNION=='Nei',
C00_MALF_ALL=='Nei')

mfr= filter(mfr, spont== 1)

q1= q1 %>% mutate(                height= ifelse(AA87>= 140 & AA87<= 210, AA87, NA),
                bmi= AA85/ ((height/100)^2),
                bmi= ifelse(bmi>15 | bmi< 45, bmi, NA))

q1= q1 %>% select(PREG_ID_315, height, AA83, AA84, bmi)

h= inner_join(h, mfr, by= 'PREG_ID_315') %>% inner_join(., q1, by= 'PREG_ID_315') %>% inner_join(., filter(link, Role== 'Child'), by= 'PREG_ID_315')

fets= inner_join(fets, link, by= 'SentrixID') %>% inner_join(., mfr, by= 'PREG_ID_315') %>% inner_join(., q1, by= 'PREG_ID_315')
moms= inner_join(moms, link, by= 'SentrixID') %>% inner_join(., mfr, by= 'PREG_ID_315') %>% inner_join(., q1, by= 'PREG_ID_315')

moms= filter(moms, SentrixID %in% flag$IID)
fets= filter(fets, SentrixID %in% flag$IID)
h= filter(h, SentrixID %in% flag$IID)

moms= moms %>% filter(!(SentrixID %in% SelectRelated(kin, moms$SentrixID)))

fets= fets %>% filter(!(SentrixID %in% SelectRelated(kin, fets$SentrixID)))

h= h %>% filter(!(SentrixID %in% SelectRelated(kin, h$SentrixID)))

df_all= inner_join(moms, fets, by= 'PREG_ID_315') %>% inner_join(., h, by= 'PREG_ID_315')

fets= select(fets, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, fets_height_GRS)
moms= select(moms, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, moms_height_GRS)
h= select(h, height, bmi, SVLEN_UL_DG, LENGDE, VEKT, h1_height_GRS, h2_height_GRS, h3_height_GRS)

df_all= select(df_all, fets_height_GRS, moms_height_GRS, h1_height_GRS, h2_height_GRS, h3_height_GRS)


fets$cohort= coh
moms$cohort= coh
h$cohort= coh
df_all$cohort= coh

h_all= c(h_all, list(h))
moms_all= c(moms_all,  list(moms))
fets_all= c(fets_all, list(fets))
alldf_all= c(alldf_all, list(df_all))

}

moms= do.call(bind_rows, moms_all)
fets= do.call(bind_rows, fets_all)
h= do.call(bind_rows, h_all)
df_all= do.call(bind_rows, alldf_all)

moms$cohort= factor(moms$cohort, levels= c('harvestm12', 'harvestm24', 'rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay'))
fets$cohort= factor(fets$cohort, levels= c('harvestm12', 'harvestm24', 'rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay'))
h$cohort= factor(h$cohort, levels= c('harvestm12', 'harvestm24', 'rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay'))
df_all$cohort= factor(df_all$cohort, levels= c('harvestm12', 'harvestm24', 'rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay'))

```


