import pandas as pd
import numpy as np
import os
import gzip
from functools import reduce
import scipy.stats as st
import statsmodels.stats.multitest as multi

cohort_nms= ['harvestm12', 'harvestm24','rotterdam1', 'rotterdam2', 'normentfeb', 'normentmay']
smpl_nms= ['maternal','paternal', 'fetal']
batch_nms= ['m12', 'm24']
CHR_nms= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12 ,13 ,14 ,15 ,16 ,17 ,18 ,19 ,20 ,21 ,22]

# Other arguments:

pruning_nms= ['none', 'soft', 'moderate', 'hard']

dens_nms= [5]
SNP_nms= [15, 25, 50, 75, 100, 150, 200, 350, 500]
length_nms= [0.0000001]
het_nms= [0, 1]
GAP_nms= [5]

dens_bp= [5000]
SNP_bp= [15, 25, 50, 75, 100, 150, 200, 350, 500]
length_bp= [0.0000001]
het_bp= [0, 1]
GAP_bp= [5000]

# Functions

def isfloat(str):
    try:
        float(str)
        return True
    except ValueError:
        return False


rule html_meta_report:
        'Generate report for all cohorts together.'
        input:
                expand('/mnt/work/pol/ROH/{cohort}/pheno/runs_mfr_{sample}.txt', cohort= cohort_nms, sample= smpl_nms),
                expand('/mnt/work/pol/{cohort}/pheno/q1_v9.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/runs/frequency/ROH_frequency_{sample}', cohort= cohort_nms, sample= smpl_nms),
                expand('/mnt/work/pol/ROH/{cohort}/genotypes/{pruning}/pruned{cohort}_{sample}.bim', cohort= cohort_nms, pruning= pruning_nms, sample= smpl_nms),
                expand('/mnt/work/pol/ROH/{cohort}/genotypes/{pruning}/cm_pruned{cohort}_{sample}.bim', cohort= cohort_nms, pruning= pruning_nms, sample= smpl_nms),
                expand('/mnt/work/pol/ROH/arguments/arg_R2_{cohort}.txt',cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/arguments/max_R2_{cohort}.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/results/het/{sample}_excess_hom.txt', cohort= cohort_nms, sample= smpl_nms),
                expand('/mnt/work/pol/ROH/{cohort}/ibd/parental_ibd.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/pheno/{cohort}_trios.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/{cohort}/pca/{cohort}_pca.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/ibd/to_phase.fam', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/genotypes/none/pruned{cohort}_fetal.fam', cohort= cohort_nms),
                expand('/mnt/work/pol/{cohort}/pheno/flag_list.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/pheno/{cohort}_trios.txt', cohort= cohort_nms),
                expand('/mnt/work/pol/{cohort}/relatedness/all_{cohort}.kin0', cohort= cohort_nms),
                expand('/mnt/work/pol/ROH/{cohort}/results/ROH_frequency_{sample}.txt', cohort= cohort_nms, sample= smpl_nms)
        output:
                'reports/html_meta_ROH_analysis.html'
        script:
                'scripts/reports/html_meta_ROH.Rmd'

rule beamer_meta_report:
	''
	input:
		'/mnt/cargo/pol/Carlos_segundo80.png',
		'/mnt/cargo/pol/ROH_parental_genetic.pdf',
		'/mnt/work/pol/ROH/tables/table_descr_cohorts.txt',
		'/mnt/work/pol/ROH/tables/pvalues_descr_cohorts.txt',
		'/mnt/work/pol/ROH/figures/hazard_multi_cohort.eps',
		'/mnt/work/pol/ROH/figures/figure1A.eps',
		'/mnt/work/pol/ROH/figures/figure1B.eps',
		'/mnt/work/pol/ROH/figures/S2_figure.eps',
		'/mnt/work/pol/ROH/tables/S1_table.txt',
		'/mnt/work/pol/ROH/figures/S3_figure.eps',
		'/mnt/work/pol/ROH/figures/figure2.eps',
		'/mnt/work/pol/ROH/figures/ROH_frequency.eps',
		'/mnt/work/pol/ROH/figures/zscore_mht_moms.eps',
		'/mnt/work/pol/ROH/annotation/independent_OMIM_HC_maternal.txt',
		'/mnt/work/pol/ROH/results/ROH_freq_maternal.txt',
		'/mnt/work/pol/ROH/figures/zscore_mht_fets.eps',
		'/mnt/work/pol/ROH/annotation/independent_OMIM_HC_fetal.txt',
		'/mnt/work/pol/ROH/results/ROH_freq_fetal.txt',
		'/mnt/cargo/pol/F1.large.jpg',
		'/mnt/cargo/pol/ROH_parental_genetic1.pdf',
		'/mnt/cargo/pol/ROH_parental_genetic2.pdf',
		'/mnt/work/pol/ROH/annotation/genes_imputed_maternal.txt',
		'/mnt/work/pol/ROH/annotation/genes_imputed_fetal.txt'
	output:
		'/mnt/work/pol/ROH/reports/meta_beamer_ROH.pdf'
	script:
		'meta_beamer.Rmd'


rule figures_pdf:
        ''
        input:
                '/mnt/work/pol/ROH/figures/figure1A.eps',
                '/mnt/work/pol/ROH/figures/figure1B.eps',
                '/mnt/work/pol/ROH/figures/figure2.eps',
                '/mnt/work/pol/ROH/figures/zscore_mht_moms.eps',
                '/mnt/work/pol/ROH/figures/zscore_mht_fets.eps'
        output:
                '/mnt/work/pol/ROH/reports/Figures.pdf'
        script:
                'figures_and_tables.Rmd'

rule supplementary_material_pdf:
        ''
        input:
                '/mnt/work/pol/ROH/tables/table_descr_cohorts.txt',
                '/mnt/work/pol/ROH/tables/pvalues_descr_cohorts.txt',
                '/mnt/work/pol/ROH/figures/hazard_multi_cohort.eps',
                '/mnt/work/pol/ROH/figures/S2_figure.eps',
                '/mnt/work/pol/ROH/tables/S1_table.txt',
                '/mnt/work/pol/ROH/figures/S3_figure.eps',
                '/mnt/work/pol/ROH/figures/ROH_frequency.eps',
                '/mnt/work/pol/ROH/annotation/independent_OMIM_HC_maternal.txt',
                '/mnt/work/pol/ROH/results/ROH_freq_maternal.txt',
                '/mnt/work/pol/ROH/annotation/independent_OMIM_HC_fetal.txt',
                '/mnt/work/pol/ROH/results/ROH_freq_fetal.txt',
                '/mnt/work/pol/ROH/annotation/genes_imputed_maternal.txt',
                '/mnt/work/pol/ROH/annotation/genes_imputed_fetal.txt'
	output:
		''
	script:
		''
